version: 0.2.0

# Monitor folder or files in windows/unix syntax.
monitor: 
# Possible monitored folders (Windows examples)
#  - path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
#   ignore: .log
#  - path: C:\Program Files
# Possible monitored folders (Linux examples)
#  - path: /etc/
#      ignore: .cfg
#  - path: /usr/bin/
#  - path: /bin/
  - path: C:\
    ignore: .log

# Path to output and events files:
# output to write app log.
# events to write monitorized folder/files events.
log: 
  output: 
    file: fim.log
    # Possible levels debug, info, error, warning
    level: debug
  events:
    file: events.json
    # Format of output events options json/syslog
    format: json