# Monitor folder or files in windows/unix syntax.
monitor: 
  - C:\tmp\

# Path to output and events files:
# output to write app log.
# events to write monitorized folder/files events.
log: 
  output: 
    file: fim.log
    # Possible levels debug, info, error, warning
    level: debug
  events:
    file: events.json
    # Format of output events options json/syslog
    format: json