node: "FIM"

# Events configuration, where to store produced events
events:
  destination: file
  file: /var/lib/fim/events.json

# Monitor files and folders.
monitor:
  - path: /tmp/
  - path: /bin/
  - path: /usr/bin/
    labels: ["usr/bin", "macos"]
  - path: /etc
    labels: ["etc", "macos"]

# Database for files checksum storage
hashscanner:
  file: /var/lib/fim/fim.db

# App procedure and errors logging
log:
  file: /var/log/fim/fim.log
  # Available levels [debug, info, error, warning]
  level: info