#!/bin/sh

# Copyright (C) 2021, Achiefs.

set -e

INSTALL_DIR="/usr"
CONFIG_DIR="/etc/fim"
DOC_DIR="${INSTALL_DIR}/share/doc/fim"

case "$1" in
    remove|failed-upgrade|abort-install|abort-upgrade|disappear)
        rm -rf ${INSTALL_DIR}/bin/fim
    ;;

    purge)
        rm -rf ${CONFIG_DIR}
        rm -rf ${DOC_DIR}
    ;;

    upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
