name: Code testing
on: [push]
jobs:
  Compilation-test-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building the rust code
        run: cargo build
      - run: echo "Job's status is ${{ job.status }}."

  Compilation-test-windows:
    runs-on: windows-2019
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building the rust code
        run: cargo build
      - run: echo "Job's status is ${{ job.status }}."

  Unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Change configuration to test
        run: sed -i 's|/var/lib/fim/events.json|./events.json|g' config/linux/config.yml
      - name: Launch cargo test
        run: cargo test
      - run: echo "Job's status is ${{ job.status }}."

  Static-analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Launch cargo clippy
        run: cargo clippy
      - run: echo "Job's status is ${{ job.status }}."