name: Code testing
on: [push]
jobs:
  Compilation-test-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building the rust code
        run: cargo build
      - run: echo "Job's status is ${{ job.status }}."

  Compilation-test-windows:
    runs-on: windows-2019
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building the rust code
        run: cargo build
      - run: echo "Job's status is ${{ job.status }}."

  Compilation-test-macos:
    runs-on: macos-11
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building the rust code
        run: cargo build
      - run: echo "Job's status is ${{ job.status }}."

  Unit-tests-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Create config folder
        run: sudo mkdir -p /etc/fim/ && sudo chown -R runner:runner /etc/fim
      - name: Create events file and folder
        run: sudo mkdir -p /var/lib/fim/ && sudo touch /var/lib/fim/events.json && sudo chown -R runner:runner /var/lib/fim
      - name: Create log file and folder
        run: sudo mkdir -p /var/log/fim/ && sudo touch /var/log/fim/fim.log && sudo chown -R runner:runner /var/log/fim
      - name: Launch cargo test
        run: cargo test
      - run: echo "Job's status is ${{ job.status }}."

  Unit-tests-windows:
    runs-on: windows-2019
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Download Sysinternals PsTools
        run: choco install -y --no-progress sysinternals
      - name: Test with Maven
        run: PsExec64 -accepteula -l cargo test
      - run: echo "Job's status is ${{ job.status }}."

  Unit-tests-macos:
    runs-on: macos-11
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Create events file and folder
        run: sudo mkdir -p /var/lib/fim/ && sudo touch /var/lib/fim/events.json && sudo chown -R runner:runner /var/lib/fim
      - name: Create log file and folder
        run: sudo mkdir -p /var/log/fim/ && sudo touch /var/log/fim/fim.log && sudo chown -R runner:runner /var/log/fim
      - name: Launch cargo test
        run: sudo cargo test
      - run: echo "Job's status is ${{ job.status }}."