name: Code testing
on: [push]
jobs:
  Compilation-test:
    runs-on: [ubuntu-20.04, windows-2019]
    steps:
      - name: Check out repository code, branch='{{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building the rust code
        run: cargo build
      - run: echo "Job's status is ${{ job.status }}."
