name: Code testing
on: [push]
jobs:
  Compilation-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          cargo build
      - run: echo "Job's status is ${{ job.status }}."
