name: Install test
on: [push]
jobs:
  Build-install-windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Building package
        run: ./builder.ps1
        working-directory: ./pkg/msi

      - name: Installing package
        run: ./fim*.msi /q /l*v msi.log
        working-directory: ./pkg/msi

      - name: Print install log
        run: cat msi.log
        working-directory: ./pkg/msi

      - name: Start FIM service
        run: NET START FimService

      - name: Check FIM is running
        run: NET START | findstr "File Integrity"


  Build-install-ubuntu:
    runs-on:
      group: Default
      labels: ubuntu18
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Building package
        run: sudo ./builder.sh
        working-directory: ./pkg/deb

      - name: Installing package
        run: sudo dpkg --install ./fim*.deb
        working-directory: ./pkg/deb

      - name: Start FIM service
        run: sudo systemctl start fim

      - name: Check FIM running
        run: sudo systemctl status fim

      - name: Remove package installation
        if: always()
        run: sudo dpkg --purge fim


  Build-install-centos:
    runs-on:
      group: centos7
    env:
      repodir: ${{ github.workspace }}/${{ github.run_id }}
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        run: git clone https://github.com/${{ github.repository }}.git -b ${{ github.ref_name }} $repodir

      - name: Building package
        run: sudo ./builder.sh
        working-directory: ${{ github.run_id }}/pkg/rpm

      - name: Installing package
        run: sudo yum install -y ./fim*.rpm
        working-directory: ${{ github.run_id }}/pkg/rpm

      - name: Start FIM service
        run: sudo systemctl start fim

      - name: Check FIM running
        run: sudo systemctl status fim

      - name: Remove package installation
        if: always()
        run: sudo yum remove -y fim

      - name: Remove repository
        if: always()
        run: sudo rm -rf $repodir


  Build-install-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Building package
        run: sudo ./builder.sh
        working-directory: ./pkg/macos

      - name: Installing package
        run: sudo installer -pkg fim*.pkg -target /
        working-directory: ./pkg/macos

      - name: Start FIM service
        run: sudo launchctl load -w /Library/LaunchDaemons/com.Achiefs.fim.launchd.plist

      - name: Check FIM running
        run: sudo launchctl print system/com.Achiefs.fim | grep "state = running"