name: Install test
on: [push]
jobs:
  Build-install-windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building package
        run: ./builder.ps1
        working-directory: ./pkg/msi
      - name: Installing package
        run: ./fim*.msi /q /l*v msi.log
        working-directory: ./pkg/msi
      - name: Print install log
        run: cat msi.log
        working-directory: ./pkg/msi
      - name: Start FIM service
        run: NET START FimService
      - name: Check FIM is running
        run: NET START | findstr "This should throw error"