name: Install test
on: [push]
jobs:
  Build-install-windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building package
        run: ./builder.ps1
        working-directory: ./pkg/msi