name: Pkg build
on: [push]
jobs:
  Pkg-build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Install required dependencies
        run: sudo apt install -y curl devscripts equivs tar gcc
      - name: Building package
        run: cd pkg/deb && sudo ./builder.sh
      - run: echo "Job's status is ${{ job.status }}."

  Pkg-build-windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Building code
        run: cargo build --release
      - name: Copying EXE to pkg folder
        run: cp target/release/fim.exe pkg/msi
      - name: Building package
        run: cd pkg/msi && candle.exe .\fim.wxs && light.exe -ext WixUIExtension .\fim.wixobj
      - run: echo "Job's status is ${{ job.status }}."