name: Pkg build
on: [push]
jobs:
  Pkg-build-ubuntu20:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Change sources.list repositories to archive Ubuntu
        run: sudo sed -i "s|http://azure.archive.ubuntu.com|http://archive.ubuntu.com|g" /etc/apt/sources.list
      - name: Install required dependencies
        run: sudo apt update -y && sudo apt install -y curl devscripts equivs tar gcc
      - name: Ubuntu 20.04 - Package build
        run: sudo ./builder.sh
        working-directory: ./pkg/deb
      - run: echo "Job's status is ${{ job.status }}."

  Pkg-build-windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Windows Server 2022 - Package build
        run: ./builder.ps1
        working-directory: ./pkg/msi
      - run: echo "Job's status is ${{ job.status }}."

  Pkg-build-centos7:
    runs-on:
      group: Default
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: CentOS 7 - Package build
        run: sudo docker run --rm okynos/fim-builder:centos7 ${{ github.ref_name }}

  Pkg-build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: macOS 11 - Package build
        run: sudo ./builder.sh
        working-directory: ./pkg/macos
      - run: echo "Job's status is ${{ job.status }}."