name: System tests
on: [push]
jobs:
  system-tests-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code, branch='${{ github.ref }}'
        uses: actions/checkout@v2
      - name: Install pytest
        run: pip3 install pytest
      - name: Build FIM
        run: cargo build
      - name: Start FIM process
        run: sudo cargo run &
      - name: Launch test suite
        run: pytest test/system/test_system.py -v
      - run: echo "Job's status is ${{ job.status }}."
